### ISSUE TITLE
Amazon EC2 check

### ISSUE THREAD

**Issue by yatish27** [aadisriram/nodejs-linkedin-scraper#2]
Did you check if this works on Amazon EC2 instance ?

**Comment by danieljoppi** [comment]
yes ... I am using in EC2 with io.js 1.8.1

**Comment by aadisriram** [comment]
Looks like @danieljoppi fixed this.

**Comment by yatish27** [comment]
Can you post the PR which adds this functionality. Or does io.js take care of it ?

**Comment by danieljoppi** [comment]
LinkedIn blocked Amazon IPs ... You need a proxy configuration
